### ISSUE TITLE
`test_linux_network_stacksmash_64` is failing in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/rex#99] opened 2023-01-30 19:55 UTC
### Description

`test_linux_network_stacksmash_64` is failing in CI frequently for the past couple weeks.

**Comment by Kyle-Kyle** [comment] 2024-01-31 21:22
closed as we are not seeing it recently

**Closed by Kyle-Kyle** 2024-01-31 21:22 UTC
Labels: bug, needs-triage

**Comment by Kyle-Kyle** [comment] 2026-05-19 06:02
I cannot reproduce it locally. But according to the log (desync in tracer), I suspect it has something to do with qtrace.

**Comment by mborgerson** [comment] 2026-05-19 08:09
@Kyle-Kyle I did not investigate deeply, but it seems related to the recent upgrade to Python 3.12 in CI. Did you try with Python 3.12 locally?
